### ISSUE TITLE
API-Created Groups Cannot Be Deleted From UI

### ISSUE THREAD

**Issue by estein9825** [paralus/paralus#152]
### Expected vs actual behavior

Not sure if this is intentional, but if you create any groups through the API, they aren't deletable from within the UI

### Steps to reproduce the bug

1. Create a group through the API
2. Log into the UI and go to groups
3. The delete option is disabled

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

```
VERSION: 0.1.0
BUILD: 0.1.0
BUILD-TIME: 1656329967
ARCH: darwin/amd64
```

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!
kubectl
```
clientVersion:
  buildDate: "2022-08-23T17:44:59Z"
  compiler: gc
  gitCommit: a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2
  gitTreeState: clean
  gitVersion: v1.25.0
  goVersion: go1.19
  major: "1"
  minor: "25"
  platform: darwin/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-11-29T18:41:42Z"
  compiler: gc
  gitCommit: 52e500d139bdef42fbc4540c357f0565c7867a81
  gitTreeState: clean
  gitVersion: v1.22.16-eks-ffeb93d
  goVersion: go1.16.15
  major: "1"
  minor: 22+
  platform: linux/amd64
```
Helm
```
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
```
### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

Workaround is to delete from the API

- [X ] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [X ] I'm using the latest version of the project.
