### ISSUE TITLE
Relay Server::failed to register relay with peer-service-bootstrap service

### ISSUE THREAD

**Issue by matixoooo** [paralus/paralus#170]
### Expected vs actual behavior
Expect starting application and access to GUI.

Actual state 

![image](https://user-images.githubusercontent.com/92515985/221866682-28670bb1-775e-43b3-a90e-753c8b854a17.png)

-

### Are you using the latest version of the project?

Yes latest version v0.2.1 

-

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

kubectl version -o=yaml

```
clientVersion:
  buildDate: "2021-03-18T01:10:43Z"
  compiler: gc
  gitCommit: 6b1d87acf3c8253c123756b9e61dac642678305f
  gitTreeState: clean
  gitVersion: v1.20.5
  goVersion: go1.15.8
  major: "1"
  minor: "20"
  platform: linux/amd64
serverVersion:
  buildDate: "2022-01-20T20:54:27Z"
  compiler: gc
  gitCommit: 3df878a25bbfc3ab7c5ab8bd99c39513fbe53c26
  gitTreeState: clean
  gitVersion: v1.22.6+vmware.1
  goVersion: go1.16.12
  major: "1"
  minor: "22"
  platform: linux/amd64
```

helm version
```
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}
```
