### ISSUE TITLE
Cannot install Paralus when using a managed PostgreSQL database

### ISSUE THREAD

**Issue by prometherion** [paralus/paralus#252]
### Expected vs actual behavior

I'm running locally a cloudnative-pg instance and trying to use it to host the Paralus data, however, I'm not able to get it up and running.

### Steps to reproduce the bug

- Install `cloudnative-pg`
- Create a pgsql Cluster

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paralus
  namespace: paralus-system
spec:
  instances: 2
  storage:
    size: 16Gi
```
- Install Paralus using the Helm chart and the following values

```yaml
# values.yaml
fqdn:
  domain: redacted.tld
  hostname: paralus
  coreConnectorSubdomain: "*.core-connector"
  userSubdomain: "*.user"
paralus:
  initialize:
    partner: Redacted
    partnerDesc: Redacted
    partnerHost: redacted.tld
    org: Redacted
    orgDesc: Redacted
    adminEmail: admin@redacted.tld
    adminFirstName: "Admin"
    adminLastName: "User"
analytics:
  enable: false
deploy:
  kratos:
    enable: false
    adminAddr: Redacted
    publicAddr: Redacted
  postgresql:
    enabled: false
    address: paralus-rw.paralus-system.svc
    username: postgres
    password: V7ABW9wTlNH0gC6ieKkXxmIHcxm66o6BfWmvyjTs03yx3ifjYihQeMThFhDaEXfg
    database: app
  contour:
    enable: false
```

### Are you using the latest version of the project?

```
NAME    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART           APP VERSION
paralus paralus-system  1               2023-09-11 15:52:52.157432395 +0200 CEST        deployed        ztka-0.2.4      v0.2.3
```

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

Running locally on Kind, vanilla Kubernetes.

cloudnative-pg installed using Helm

```
NAME            NAMESPACE               REVISION        UPDATED                                         STATUS          CHART                   APP VERSION
cnpg            cnpg-system             1               2023-09-06 15:04:58.159471577 +0000 UTC         deployed        cloudnative-pg-0.18.2   1.20.2
```

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

-

- [x] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [ ] I'm using the latest version of the project.

**Comment by akshay196** [comment]
@prometherion I tried cloudnative-pg and paralus locally on a Kind cluster. It is working fine.
I have used `app` user (default cloudnative-pg user) and its password instead of `postgres`. - https://cloudnative-pg.io/documentation/1.20/bootstrap/

```
$ kubectl get pod
NAME                                         READY   STATUS    RESTARTS      AGE
cluster-example-1                            1/1     Running   0             34m
dashboard-6fdb498f8b-ft2nj                   1/1     Running   0             18m
myrelease-contour-contour-7fccf45974-7ww7g   1/1     Running   0             18m
myrelease-contour-envoy-d8hlz                2/2     Running   0             18m
myrelease-fluent-bit-gn27w                   1/1     Running   0             18m
myrelease-kratos-courier-0                   2/2     Running   0             18m
myrelease-kratos-f4b895987-phpdc             2/2     Running   0             18m
paralus-5fc66f7d49-lf6pk                     2/2     Running   0             18m
prompt-6d9cf67478-f7jmj                      2/2     Running   0             18m
relay-server-74fb9fb87f-59ph7                2/2     Running   6 (10m ago)   18m
```

> error: Dirty database version 21. Fix and force version.

Can you provide `--previous` flag to kubectl logs command and get the initial error occurred?

**Comment by prometherion** [comment]
I found the solution to the reported issue.

When `kratos` is disabled, as well as missing the `kratos.kratos.development=true`, the migration issue is faced: with the following values everything was up and ready.

```yaml
analytics:
  enable: false
deploy:
  contour:
    enable: false
  postgresql:
    address: paralus-rw.paralus-system.svc
    database: app
    password: <REDACTED>
    username: postgres
fqdn:
  coreConnectorSubdomain: <REDACTED>
  domain: <REDACTED>
  hostname: <REDACTED>
  userSubdomain: <REDACTED>
kratos:
  kratos:
    development: true
ingress:
  enabled: true
  className: <REDACTED>
```

It wasn't clear to me how the components work together, and why Kratos is required. Not sure if it's me who didn't pay enough attention to the documentation, or if it's missing some required RTFM section (sarcasm on).
