### ISSUE TITLE
API Key and secret issue

### ISSUE THREAD

**Issue by soontobemil** [paralus/paralus#348]
### Expected vs actual behavior

Expected Behavior:
A user with specific permissions should be able to generate an API key and secret for a single project without requiring organizational admin permissions.

Actual Behavior:
It seems that only organizational admins can generate an API key and secret. There doesn’t appear to be a way to grant a user just enough permission to generate an API key for a single project.

### Steps to reproduce the bug

1. Attempt to create a user with limited permissions (not an organizational admin).
2. Try to grant this user permissions to generate an API key for a specific project.
3. Observe whether the user is able to generate an API key.

### Are you using the latest version of the project?

Yes, the latest version, v0.2.8 of helm version

-

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

Cloud Provider: Exoscale SKS 
kubectl version --output=yaml: 
```
❯ kubectl version --output=yaml
clientVersion:
  buildDate: "2024-06-11T20:20:59Z"
  compiler: gc
  gitCommit: foobar
  gitTreeState: clean
  gitVersion: v1.30.2
  goVersion: go1.22.4
  major: "1"
  minor: "30"
  platform: darwin/arm64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-07-16T23:50:57Z"
  compiler: gc
  gitCommit: foobar
  gitTreeState: clean
  gitVersion: v1.28.12
  goVersion: go1.22.5
  major: "1"
  minor: "28"
  platform: linux/amd64
  ```
helm version: v0.2.8

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

t seems that the permission model in Paralus may be too restrictive. A possible solution could involve adding a specific role or permission that allows users to generate API keys for individual projects without requiring full organizational admin rights.

- [ ] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [ ] I'm using the latest version of the project.
