### ISSUE TITLE
Unable to install paralus:  Initialize Container Fails with Proto Duplicates and PostgreSQL Constraint Violation

### ISSUE THREAD

**Issue by buvanesh-s** [paralus/paralus#391]
### Steps to Reproduce
1. Deploy Paralus using documented commands with default PostgreSQL values  
2. Check initialize container logs  
3. Observe errors preventing successful initialization  

```
 $kubectl logs -f paralus-6dcfcc744d-rv69j -c initialize
2025/06/12 03:03:13 proto: duplicate proto type registered: k8s.io.apimachinery.pkg.runtime.RawExtension
2025/06/12 03:03:13 proto: duplicate proto type registered: k8s.io.apimachinery.pkg.runtime.TypeMeta
2025/06/12 03:03:13 proto: duplicate proto type registered: k8s.io.apimachinery.pkg.runtime.Unknown
2025/06/12 03:03:13 Error running from base directory failed to create permission cli.config.read: ERROR: null value in column "created_at" of relation "authsrv_resourcepermission" violates not-null constraint (SQLSTATE=23502)

$ kubectl get pod
NAME                                          READY   STATUS                  RESTARTS        AGE
my-release1-kratos-courier-0                  2/2     Running                 0               21m
dashboard-59596c8cb-vm8s6                     1/1     Running                 0               21m
prompt-86c5dcd6dd-79p89                       2/2     Running                 0               21m
my-release1-contour-contour-9c94f7cdf-gcjs8   1/1     Running                 0               21m
my-release1-contour-envoy-t2dxz               2/2     Running                 0               21m
my-release1-contour-envoy-qzqxz               2/2     Running                 0               21m
my-release1-postgresql-0                      1/1     Running                 0               21m
my-release1-fluent-bit-qzr7q                  1/1     Running                 3 (21m ago)     21m
my-release1-fluent-bit-x8bvl                  1/1     Running                 3 (21m ago)     21m
my-release1-fluent-bit-nq996                  1/1     Running                 3 (21m ago)     21m
my-release1-fluent-bit-mlllg                  1/1     Running                 3 (21m ago)     21m
my-release1-fluent-bit-tjp2m                  1/1     Running                 3 (21m ago)     21m
my-release1-kratos-59499ccd74-tbtgj           2/2     Running                 1 (20m ago)     21m
my-release1-fluent-bit-622f4                  1/1     Running                 4 (21m ago)     21m
my-release1-fluent-bit-wjm28                  1/1     Running                 4 (21m ago)     21m
my-release1-contour-envoy-4fxjq               2/2     Running                 1 (18m ago)     21m
my-release1-contour-envoy-z4l8c               2/2     Running                 0               21m
my-release1-contour-envoy-7c85l               2/2     Running                 1 (9m30s ago)   21m
paralus-6dcfcc744d-rv69j                      0/2     Init:CrashLoopBackOff   8 (4m36s ago)   21m
relay-server-599699fcd7-8ll4w                 1/2     CrashLoopBackOff        8 (85s ago)     21m
my-release1-contour-envoy-r62hm               1/2     Running                 2 (30s ago)     21m
my-release1-contour-envoy-22vlx               1/2     Running                 4 (30s ago)     21m
```

### Are you using the latest version of the project? Yes

```
$ helm ls
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART           APP VERSION
my-release1     paralus         1               2025-06-12 04:45:32.577234412 +0200 CEST        deployed        ztka-0.3.0      v0.2.9
```
-

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output 

Civo cloud provider
```
kubectl version --output=yaml
clientVersion:
  buildDate: "2024-09-12T00:18:35Z"
  compiler: gc
  gitCommit: 74e84a90c725047b1328ff3d589fedb1cb7a120e
  gitTreeState: clean
  gitVersion: v1.30.5
  goVersion: go1.22.6
  major: "1"
  minor: "30"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-02-29T20:36:21Z"
  compiler: gc
  gitCommit: 051b14b248655896fdfd7ba6c93db6182cde7431
  gitTreeState: clean
  gitVersion: v1.28.7+k3s1
  goVersion: go1.21.7
  major: "1"
  minor: "28"
  platform: linux/amd64
```
-
