### ISSUE TITLE
Kubectl commands work even after deleting an imported cluster from the dashboard

### ISSUE THREAD

**Issue by techmaharaj** [paralus/paralus#86]
### Expected vs actual behavior

Even after I do a delete from the dashboard, and if kubectl is already open, I'm still able to perform operations on the cluster for a few minutes. Only after a while it starts throwing error. (_image attached_)

### Steps to reproduce the bug

1. Import a cluster to Paralus
2. Open web kubectl (prompt) & execute some command i.e. `kubectl get pods`
3. Delete the cluster from the UI, but clicking the delete cluster. _Ensure the web-kubectl screen is still open_
4. After the cluster has been deleted from the UI, execute another command `kubectl create ns testns` followed by a 'kubectl get ns' - you'll observe that the namespace is created as well as listing command works even though the cluster is deleted from the UI.

### Are you using the latest version of the project?

```sh
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART     	APP VERSION
myrelease	paralus  	1       	2022-10-14 19:08:59.321602061 +0530 IST	deployed	ztka-0.1.7	v0.1.6    
```

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

```yaml
clientVersion:
  buildDate: "2022-05-03T13:46:05Z"
  compiler: gc
  gitCommit: 4ce5a8954017644c5420bae81d72b09b735c21f0
  gitTreeState: clean
  gitVersion: v1.24.0
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-08-17T18:47:37Z"
  compiler: gc
  gitCommit: 95ee5ab382d64cfe6c28967f36b53970b8374491
  gitTreeState: clean
  gitVersion: v1.24.4
  goVersion: go1.18.5
  major: "1"
  minor: "24"
  platform: linux/amd64

```
## Screenshot

![image](https://user-images.githubusercontent.com/10296271/196086283-13e706e5-7a71-4365-b928-00a70da58061.png)

### Suggestions

Can we do something about it? Like maybe running a `kubectl delete ns paralus-system` in the background as soon as the cluster is deleted from the UI.

- [x] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [x] I'm using the latest version of the project.
